name: Pull request
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
      - labeled
      - unlabeled

jobs:
  check_labels:
    name: Check labels
    runs-on: ubuntu-latest
    steps:
      - uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          none_of: draft
          repo_token: ${{ secrets.GITHUB_TOKEN }}

  check_tasks:
    name: Check tasks
    runs-on: ubuntu-latest
    steps:
      - name: Check tasks
        uses: sumally/github-check-tasklist-action@v1.0.0
